### DermAI Diagnostics

 ### Data Preprocessing


- Loading the cleaned dataset
- Feature selection
- Identifying target and predictor variables
- Preventing data leakage
- Train-test splitting
- Building preprocessing pipelines
- Encoding categorical variables
- Scaling numerical variables
- Preparing data for model development

### STEP 1 - Import Relevant Libraries

In [1]:
import os
import warnings

import joblib
import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline

from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)

from sklearn.impute import SimpleImputer

### STEP 2 — Load Dataset

In [2]:

DATA_PATH = os.path.join(
    "..",
    "data",
    "raw",
    "dermai_ml_ready.csv"
)

df = pd.read_csv(DATA_PATH)

df.head()

,patient_id,age,age_group,gender,smoke,drink,pesticide,skin_cancer_history,cancer_history,has_piped_water,...,lesion_size_category,itch,grew,hurt,changed,bleed,elevation,biopsed,diagnostic,cancerous_flag
0,PAT_100,14,Young Adult,MALE,f,f,f,f,t,f,...,Medium,f,f,f,f,f,f,t,NEV,0
1,PAT_1000,65,Older Adult,MALE,f,f,f,f,f,f,...,Small,f,f,f,f,f,f,f,SEK,0
2,PAT_1006,63,Older Adult,MALE,f,f,f,f,f,f,...,Small,f,f,f,f,f,f,f,ACK,0
3,PAT_1008,64,Older Adult,MALE,f,f,f,f,f,f,...,Small,f,t,f,f,f,t,f,SEK,0
4,PAT_101,59,Older Adult,MALE,t,t,f,f,f,t,...,Large,t,t,t,f,t,t,t,BCC,1

### STEP 3 — Dataset Overview

In [3]:
print(df.shape)

df.info()

(1088, 29)
<class 'pandas.DataFrame'>
RangeIndex: 1088 entries, 0 to 1087
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   patient_id            1088 non-null   str
 1   age                   1088 non-null   int64
 2   age_group             1088 non-null   str
 3   gender                1088 non-null   str
 4   smoke                 1088 non-null   str
 5   drink                 1088 non-null   str
 6   pesticide             1088 non-null   str
 7   skin_cancer_history   1088 non-null   str
 8   cancer_history        1088 non-null   str
 9   has_piped_water       1088 non-null   str
 10  has_sewage_system     1088 non-null   str
 11  background_father     1088 non-null   str
 12  background_mother     1088 non-null   str
 13  lesion_id             1088 non-null   int64
 14  fitspatrick           1088 non-null   int64
 15  region                1088 non-null   str
 16  diameter_1            1088 non-null   int64
 17  diameter_2            1088 non-null   int64
 18  avg_diameter          1088 non-null   float64
 19  lesion_size_category  1088 non-null   str
 20  itch                  1088 non-null   str
 21  grew                  1088 non-null   str
 22  hurt                  1088 non-null   str
 23  changed               1088 non-null   str
 24  bleed                 1088 non-null   str
 25  elevation             1088 non-null   str
 26  biopsed               1088 non-null   str
 27  diagnostic            1088 non-null   str
 28  cancerous_flag        1088 non-null   int64
dtypes: float64(1), int64(6), str(22)
memory usage: 246.6 KB

### STEP 4 — Drop Non-Predictive Columns

In [4]:
# step 4a- Drop Identifier Columns
identifier_cols = [
    "patient_id",
    "lesion_id"
]

df = df.drop(
    columns=identifier_cols,
    errors="ignore"
)

In [5]:
# step 4b - Drop leakage columns
leakage_cols = [
    "diagnostic",
    "biopsed"
]

df = df.drop(
    columns=leakage_cols,
    errors="ignore"
)

### STEP 5 — Define Features and Target

In [6]:

X = df.drop(
    columns="cancerous_flag"
)

y = df["cancerous_flag"]

### STEP 6 — Identify Feature Types

In [7]:

numerical_cols = X.select_dtypes(
    include=np.number
).columns.tolist()

categorical_cols = X.select_dtypes(
    exclude=np.number
).columns.tolist()

print("Numerical Features:", len(numerical_cols))
print("Categorical Features:", len(categorical_cols))

Numerical Features: 5
Categorical Features: 19

In [8]:
print(numerical_cols)
print(categorical_cols)

['age', 'fitspatrick', 'diameter_1', 'diameter_2', 'avg_diameter']
['age_group', 'gender', 'smoke', 'drink', 'pesticide', 'skin_cancer_history', 'cancer_history', 'has_piped_water', 'has_sewage_system', 'background_father', 'background_mother', 'region', 'lesion_size_category', 'itch', 'grew', 'hurt', 'changed', 'bleed', 'elevation']

### STEP 7 — Train-Test Split

In [9]:
# step 7a - Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [10]:
# step 7b -  Check the split
print("Training set:", X_train.shape)
print("Testing set :", X_test.shape)

print()

print("Training target distribution")
print(y_train.value_counts(normalize=True))

print()

print("Testing target distribution")
print(y_test.value_counts(normalize=True))

Training set: (870, 24)
Testing set : (218, 24)

Training target distribution
cancerous_flag
0    0.681609
1    0.318391
Name: proportion, dtype: float64

Testing target distribution
cancerous_flag
0    0.683486
1    0.316514
Name: proportion, dtype: float64

### STEP 8 — Build the Preprocessing Pipeline

In [11]:
# step 8a - Numeric pipeline

numerical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)

numerical_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())])

In [12]:
# step 8b -  categorical pipeline

categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            )
        )
    ]
)

categorical_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

In [13]:
# step 8c -  combine both pipeline

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numerical_pipeline,
            numerical_cols
        ),
        (
            "cat",
            categorical_pipeline,
            categorical_cols
        )
    ],
    remainder="drop"
)

preprocessor

ColumnTransformer(transformers=[('num',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'fitspatrick', 'diameter_1',
                                  'diameter_2', 'avg_diameter']),
                                ('cat',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['age_group', 'gender', 'smoke', 'drink',
                                  'pesticide', 'skin_cancer_history',
                                  'cancer_history', 'has_piped_water',
                                  'has_sewage_system', 'background_father',
                                  'background_mother', 'region',
                                  'lesion_size_category', 'itch', 'grew',
                                  'hurt', 'changed', 'bleed', 'elevation'])])

### STEP 9 — Fit on Training Data Only

In [14]:
# step 9a - fit the data
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [15]:
# step 9b -  verify the transformed shapes:

print("Original training shape:", X_train.shape)
print("Processed training shape:", X_train_processed.shape)

print()

print("Original testing shape:", X_test.shape)
print("Processed testing shape:", X_test_processed.shape)

Original training shape: (870, 24)
Processed training shape: (870, 75)

Original testing shape: (218, 24)
Processed testing shape: (218, 75)

### STEP 10 — Retrieve Feature Names

In [16]:
# step 10 - retrieved feature names

feature_names = preprocessor.get_feature_names_out()

print(f"Total processed features: {len(feature_names)}")
print(feature_names)

Total processed features: 75
['num__age' 'num__fitspatrick' 'num__diameter_1' 'num__diameter_2'
 'num__avg_diameter' 'cat__age_group_Elderly' 'cat__age_group_Middle Age'
 'cat__age_group_Older Adult' 'cat__age_group_Young Adult'
 'cat__gender_FEMALE' 'cat__gender_MALE' 'cat__smoke_f' 'cat__smoke_t'
 'cat__drink_f' 'cat__drink_t' 'cat__pesticide_f' 'cat__pesticide_t'
 'cat__skin_cancer_history_f' 'cat__skin_cancer_history_t'
 'cat__cancer_history_f' 'cat__cancer_history_t' 'cat__has_piped_water_f'
 'cat__has_piped_water_t' 'cat__has_sewage_system_f'
 'cat__has_sewage_system_t' 'cat__background_father_AUSTRIA'
 'cat__background_father_BRAZIL' 'cat__background_father_GERMANY'
 'cat__background_father_ISRAEL' 'cat__background_father_ITALY'
 'cat__background_father_NETHERLANDS' 'cat__background_father_POLAND'
 'cat__background_father_POMERANIA' 'cat__background_father_PORTUGAL'
 'cat__background_father_UNK' 'cat__background_father_UNKNOWN'
 'cat__background_mother_BRAZIL' 'cat__background_mother_FRANCE'
 'cat__background_mother_GERMANY' 'cat__background_mother_ITALY'
 'cat__background_mother_NETHERLANDS' 'cat__background_mother_POMERANIA'
 'cat__background_mother_PORTUGAL' 'cat__background_mother_SPAIN'
 'cat__background_mother_UNK' 'cat__background_mother_UNKNOWN'
 'cat__region_ABDOMEN' 'cat__region_ARM' 'cat__region_BACK'
 'cat__region_CHEST' 'cat__region_EAR' 'cat__region_FACE'
 'cat__region_FOOT' 'cat__region_FOREARM' 'cat__region_HAND'
 'cat__region_LIP' 'cat__region_NECK' 'cat__region_NOSE'
 'cat__region_SCALP' 'cat__region_THIGH' 'cat__lesion_size_category_Large'
 'cat__lesion_size_category_Medium' 'cat__lesion_size_category_Small'
 'cat__itch_f' 'cat__itch_t' 'cat__grew_f' 'cat__grew_t' 'cat__hurt_f'
 'cat__hurt_t' 'cat__changed_f' 'cat__changed_t' 'cat__bleed_f'
 'cat__bleed_t' 'cat__elevation_f' 'cat__elevation_t']

In [17]:
# step 10b -  Create DataFrames:

X_train_processed_df = pd.DataFrame(
    X_train_processed,
    columns=feature_names,
    index=X_train.index
)

X_test_processed_df = pd.DataFrame(
    X_test_processed,
    columns=feature_names,
    index=X_test.index
)

X_train_processed_df.head()

,num__age,num__fitspatrick,num__diameter_1,num__diameter_2,num__avg_diameter,cat__age_group_Elderly,cat__age_group_Middle Age,cat__age_group_Older Adult,cat__age_group_Young Adult,cat__gender_FEMALE,...,cat__grew_f,cat__grew_t,cat__hurt_f,cat__hurt_t,cat__changed_f,cat__changed_t,cat__bleed_f,cat__bleed_t,cat__elevation_f,cat__elevation_t
151,1.246696,-0.851742,-0.725383,-0.728161,-0.737225,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
552,-0.531178,-0.851742,-0.725383,-0.728161,-0.737225,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
785,-0.224648,0.688831,0.239576,0.196117,0.224253,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0
415,0.817554,-0.851742,-0.725383,-0.728161,-0.737225,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
938,-0.224648,2.999692,-0.587532,-0.543305,-0.576979,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0

In [18]:
# step 10c -  Save the Preprocessor and Split Data
MODELS_DIR = os.path.join("..", "Models")
PROCESSED_DIR = os.path.join("..", "data", "processed")

os.makedirs(MODELS_DIR, exist_ok=True)
os.makedirs(PROCESSED_DIR, exist_ok=True)

In [19]:
# step 10d -  Save the fitted preprocessor:
joblib.dump(
    preprocessor,
    os.path.join(MODELS_DIR, "preprocessor.joblib")
)

print("Preprocessor saved successfully.")

Preprocessor saved successfully.

In [20]:
# step 10e - save split data

X_train.to_csv(
    os.path.join(PROCESSED_DIR, "X_train.csv"),
    index=False
)

X_test.to_csv(
    os.path.join(PROCESSED_DIR, "X_test.csv"),
    index=False
)

y_train.to_csv(
    os.path.join(PROCESSED_DIR, "y_train.csv"),
    index=False
)

y_test.to_csv(
    os.path.join(PROCESSED_DIR, "y_test.csv"),
    index=False
)

print("Training and testing datasets saved successfully.")

Training and testing datasets saved successfully.

## Preprocessing Summary

- Identifier columns were removed.
- `diagnostic` was excluded to prevent target leakage.
- The data was split before preprocessing.
- Numerical features were median-imputed and standardised.
- Categorical features were mode-imputed and one-hot encoded.
- The fitted preprocessing object was saved for modelling and deployment.

In [21]:
print(X.columns.tolist())

['age', 'age_group', 'gender', 'smoke', 'drink', 'pesticide', 'skin_cancer_history', 'cancer_history', 'has_piped_water', 'has_sewage_system', 'background_father', 'background_mother', 'fitspatrick', 'region', 'diameter_1', 'diameter_2', 'avg_diameter', 'lesion_size_category', 'itch', 'grew', 'hurt', 'changed', 'bleed', 'elevation']